/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSection: typeof import('./src/components/AdvancedSection.vue')['default']
    AIAnalysisDialog: typeof import('./src/components/AIAnalysisDialog.vue')['default']
    AIOverlay: typeof import('./src/components/AIOverlay.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BlurFade: typeof import('./src/components/animations/BlurFade.vue')['default']
    CategoryFilter: typeof import('./src/components/common/CategoryFilter.vue')['default']
    ChangePasswordDialog: typeof import('./src/components/auth/ChangePasswordDialog.vue')['default']
    ChannelsPanel: typeof import('./src/components/subscription/ChannelsPanel.vue')['default']
    ComparableSoftwareList: typeof import('./src/components/comparison/ComparableSoftwareList.vue')['default']
    ComparisonAIOverlay: typeof import('./src/components/ComparisonAIOverlay.vue')['default']
    ComparisonEditor: typeof import('./src/components/comparison/ComparisonEditor.vue')['default']
    ComparisonManager: typeof import('./src/components/ComparisonManager.vue')['default']
    ComparisonStructuredView: typeof import('./src/components/comparison/ComparisonStructuredView.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/common/DeleteConfirmDialog.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    FieldMessage: typeof import('./src/components/common/FieldMessage.vue')['default']
    GitHubReleases: typeof import('./src/components/software/GitHubReleases.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconUploader: typeof import('./src/components/IconUploader.vue')['default']
    InfoItem: typeof import('./src/components/subscription/InfoItem.vue')['default']
    InlineToast: typeof import('./src/components/InlineToast.vue')['default']
    ISimpleIconsApple: typeof import('~icons/simple-icons/apple')['default']
    ISimpleIconsHarmonyos: typeof import('~icons/simple-icons/harmonyos')['default']
    ISimpleIconsLinux: typeof import('~icons/simple-icons/linux')['default']
    IUilAndroid: typeof import('~icons/uil/android')['default']
    IUilWindows: typeof import('~icons/uil/windows')['default']
    LoadingOverlay: typeof import('./src/components/layout/LoadingOverlay.vue')['default']
    LoginDialog: typeof import('./src/components/auth/LoginDialog.vue')['default']
    LogsDialog: typeof import('./src/components/subscription/LogsDialog.vue')['default']
    MarkdownRenderer: typeof import('./src/components/common/MarkdownRenderer.vue')['default']
    MeowChannelForm: typeof import('./src/components/subscription/MeowChannelForm.vue')['default']
    MobileAccountSheet: typeof import('./src/components/auth/MobileAccountSheet.vue')['default']
    MobileBottomNav: typeof import('./src/components/layout/MobileBottomNav.vue')['default']
    NewArrivalRadar: typeof import('./src/components/common/NewArrivalRadar.vue')['default']
    ProsConsEditor: typeof import('./src/components/ProsConsEditor.vue')['default']
    RelatedArticlesEditor: typeof import('./src/components/RelatedArticlesEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    SelectedComparisonList: typeof import('./src/components/comparison/SelectedComparisonList.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    ShareCardPreview: typeof import('./src/components/ShareCardPreview.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    SoftwareCard: typeof import('./src/components/SoftwareCard.vue')['default']
    SoftwareCompare: typeof import('./src/components/SoftwareCompare.vue')['default']
    SoftwareDetail: typeof import('./src/components/SoftwareDetail.vue')['default']
    SoftwareDetailLoading: typeof import('./src/components/SoftwareDetailLoading.vue')['default']
    SoftwareForm: typeof import('./src/components/SoftwareForm.vue')['default']
    SoftwareGrid: typeof import('./src/components/software/SoftwareGrid.vue')['default']
    StatCard: typeof import('./src/components/subscription/StatCard.vue')['default']
    StructuredPairListEditor: typeof import('./src/components/common/StructuredPairListEditor.vue')['default']
    SubscribeButton: typeof import('./src/components/subscription/SubscribeButton.vue')['default']
    SubscriptionCard: typeof import('./src/components/subscription/SubscriptionCard.vue')['default']
    SubscriptionDialog: typeof import('./src/components/subscription/SubscriptionDialog.vue')['default']
    SystemIcon: typeof import('./src/components/SystemIcon.vue')['default']
    TagBadge: typeof import('./src/components/common/TagBadge.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    Tooltip: typeof import('./src/components/common/Tooltip.vue')['default']
    UserMenu: typeof import('./src/components/auth/UserMenu.vue')['default']
    VirtualSoftwareList: typeof import('./src/components/software/VirtualSoftwareList.vue')['default']
  }
}
