/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSection: typeof import('./src/components/AdvancedSection.vue')['default']
    AIAnalysisButton: typeof import('./src/components/AIAnalysisButton.vue')['default']
    AIAnalysisDialog: typeof import('./src/components/AIAnalysisDialog.vue')['default']
    AIOverlay: typeof import('./src/components/AIOverlay.vue')['default']
    AIOverlayEnhanced: typeof import('./src/components/AIOverlayEnhanced.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BaseButton: typeof import('./src/components/common/BaseButton.vue')['default']
    BlurFade: typeof import('./src/components/animations/BlurFade.vue')['default']
    CategoryFilter: typeof import('./src/components/common/CategoryFilter.vue')['default']
    ComparableSoftwareList: typeof import('./src/components/comparison/ComparableSoftwareList.vue')['default']
    ComparisonAIOverlay: typeof import('./src/components/ComparisonAIOverlay.vue')['default']
    ComparisonEditor: typeof import('./src/components/comparison/ComparisonEditor.vue')['default']
    ComparisonManager: typeof import('./src/components/ComparisonManager.vue')['default']
    ComparisonResult: typeof import('./src/components/ComparisonResult.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/common/DeleteConfirmDialog.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    IconButton: typeof import('./src/components/common/IconButton.vue')['default']
    IconUploader: typeof import('./src/components/IconUploader.vue')['default']
    ILogosLinuxTux: typeof import('~icons/logos/linux-tux')['default']
    ILogosMicrosoftWindows: typeof import('~icons/logos/microsoft-windows')['default']
    ISimpleIconsAndroid: typeof import('~icons/simple-icons/android')['default']
    ISimpleIconsApple: typeof import('~icons/simple-icons/apple')['default']
    ISimpleIconsHarmonyos: typeof import('~icons/simple-icons/harmonyos')['default']
    ISimpleIconsLinux: typeof import('~icons/simple-icons/linux')['default']
    ISimpleIconsMacos: typeof import('~icons/simple-icons/macos')['default']
    ISimpleIconsWindows: typeof import('~icons/simple-icons/windows')['default']
    'IUil-Android': typeof import('~icons/uil/-android')['default']
    IUilAndroid: typeof import('~icons/uil/android')['default']
    IUilWindows: typeof import('~icons/uil/windows')['default']
    LoadingOverlay: typeof import('./src/components/layout/LoadingOverlay.vue')['default']
    ProsConsEditor: typeof import('./src/components/ProsConsEditor.vue')['default']
    SearchBar: typeof import('./src/components/common/SearchBar.vue')['default']
    SelectedComparisonList: typeof import('./src/components/comparison/SelectedComparisonList.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    ShareCardPreview: typeof import('./src/components/ShareCardPreview.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    SoftwareCard: typeof import('./src/components/SoftwareCard.vue')['default']
    SoftwareCompare: typeof import('./src/components/SoftwareCompare.vue')['default']
    SoftwareDetail: typeof import('./src/components/SoftwareDetail.vue')['default']
    SoftwareForm: typeof import('./src/components/SoftwareForm.vue')['default']
    SoftwareGrid: typeof import('./src/components/software/SoftwareGrid.vue')['default']
    SystemIcon: typeof import('./src/components/SystemIcon.vue')['default']
    TagBadge: typeof import('./src/components/common/TagBadge.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    UserMenu: typeof import('./src/components/auth/UserMenu.vue')['default']
    VirtualSoftwareList: typeof import('./src/components/software/VirtualSoftwareList.vue')['default']
  }
}
